# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1079657f93090ffa2796e79faf885c8aac44676fd0272f4650bbfd1c9f1da4007377ddf0ceb91e5de03596e5ff2b6156e088d36a1dd923f3e451b799b9d44f0f

test:
  secret_key_base: f43be85f8ac3e3542a04a0be4b16faa89a2e379697b7d7541657cf5e31029de3d83941ee9f0dc3ff880ce4421b04f9a7ca1c749567cbb6ae4f6134d470244bf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
